# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hero.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhero.proto\x12\x04hero\"\x16\n\x08HeroById\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x04Hero\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t28\n\rHeroesService\x12\'\n\x07\x46indOne\x12\x0e.hero.HeroById\x1a\n.hero.Hero\"\x00\x42\x08Z\x06./herob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hero_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006./hero'
  _HEROBYID._serialized_start=20
  _HEROBYID._serialized_end=42
  _HERO._serialized_start=44
  _HERO._serialized_end=76
  _HEROESSERVICE._serialized_start=78
  _HEROESSERVICE._serialized_end=134
# @@protoc_insertion_point(module_scope)
