# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hero_pb2 as hero__pb2


class HeroesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindOne = channel.unary_unary(
                '/hero.HeroesService/FindOne',
                request_serializer=hero__pb2.HeroById.SerializeToString,
                response_deserializer=hero__pb2.Hero.FromString,
                )


class HeroesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeroesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindOne': grpc.unary_unary_rpc_method_handler(
                    servicer.FindOne,
                    request_deserializer=hero__pb2.HeroById.FromString,
                    response_serializer=hero__pb2.Hero.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hero.HeroesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HeroesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hero.HeroesService/FindOne',
            hero__pb2.HeroById.SerializeToString,
            hero__pb2.Hero.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
